// world constants
#define MAXDIMENSION 10.0f
#define MINDIMENSION -10.0f

// particle constants
#define PARTICLERADIUS 1.f


#define CUBESPERDIMENSION (MAXDIMENSION - MINDIMENSION) / (2  * PARTICLERADIUS)
#define TOTALCUBES CUBESPERDIMENSION * CUBESPERDIMENSION * CUBESPERDIMENSION