// world constants
#define MAXDIMENSION 30.0f
#define MINDIMENSION -30.0f

// particle constants
#define PARTICLERADIUS 2.0f


#define CUBESPERDIMENSION (MAXDIMENSION - MINDIMENSION) / PARTICLERADIUS
#define TOTALCUBES CUBESPERDIMENSION * CUBESPERDIMENSION * CUBESPERDIMENSION